---
# handlers file for ax25

- name: restart socat
  ansible.builtin.service:
    name: 'socat@{{ item }}'
    state: restarted
  loop: "{{ remote_tncs.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
- name: restart tnc_link
  ansible.builtin.service:
    name: 'tnc_link@{{ item }}'
    state: restarted
  loop: "{{ local_tncs.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
- name: reload ax25d
  ansible.builtin.service:
    name: ax25d
    state: restarted
