---

- hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true
  vars_prompt:
    - name: serialPort
      prompt: which serial port is your TNC connected to
      default: "/dev/ttyUSB0"
      private: no
  pre_tasks:
    - name: link tnc device
      file:
        src: "{{ serialPort }}"
        dest: /dev/tnc
        state: link
  roles:
    - role: devoinc.systemd_service
      become: True
      systemd_service:
        kissattach:
          enabled: Yes
          exec_start: "/usr/sbin/kissattach $(readlink /dev/tnc) ax0"
          restart: "on-failure"
          wanted_by: "multi-user.target"

- name: include ax25 playboot
  import_playbook: site.yml
