# This playbook along with `station.yml` is used to
# deploy ax25 client and server stacks on all reachable nodes
#
#  # XXX: a reboot is currently necessary for AX.25 data to be "seen"
---
- hosts: all
  gather_facts: no
  any_errors_fatal: true
  roles:
    - role: node
      become: True
      when: node_axport or node_nrport
    - role: rmsgw
      become: True
      sysop: "{{ rmsgw_sysop }}"
      channels: "{{ rmsgw_channels }}"
      when: rmsgw_channels
    - role: netrom
      become: True
      when: nrports
    - role: pat
      become: True
      when: patports
