---

- hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true
  vars_prompt:
    - name: callsign
      prompt: what is your callsign
      private: no
    - name: nralias
      prompt: what is your netrom alias
      private: no
    - name: nrport
      prompt: what is your netrom port number
      default: "1"
    - name: nrpassword
      prompt: what is your netrom node password 
      private: yes
  roles:
    - role: ax25
      become: True

    - role: devoinc.systemd_service
      become: True
      systemd_service:
        kissattach:
          enabled: Yes
          exec_start: "/usr/sbin/kissattach /dev/tnc ax0"
          restart: "on-failure"
          requisite: "socat.service"
          after: "socat.service"
          wanted_by: "multi-user.target"
        nrattach:
          enabled: Yes
          exec_start: "/usr/sbin/nrattach netrom"
          restart: "on-failure"
          requisite: "kissattach.service"
          after: "kissattach.service"
          wanted_by: "multi-user.target"
        mheard:
          enabled: Yes
          exec_start: "/usr/sbin/mheardd"
          restart: "on-failure"
          requisite: "kissattach.service"
          after: "kissattach.service"
          wanted_by: "multi-user.target"
        netrom:
          enabled: Yes
          exec_start: "/usr/sbin/netromd -i"
          restart: "on-failure"
          requisite: "nrattach.service"
          after: "nrattach.service"
          wanted_by: "multi-user.target"
        ax25d:
          enabled: Yes
          exec_start: "/usr/sbin/ax25d -l"
          restart: "on-failure"
          requisite: "kissattach.service"
          after: "kissattach.service"
          wanted_by: "multi-user.target"
