---
#- hosts: all
#  gather_facts: yes

- hosts: packet
  any_errors_fatal: true
  roles:
    - role: ax25
      tags: [ax25]
      become: True

    - role: devoinc.systemd_service
      tags: [systemd]
      become: True
      systemd_service:
        socat:
          enabled: Yes
          exec_start: "/usr/bin/socat PTY,link=/dev/direwolf,raw,echo=0,wait-slave TCP4:kvm:8001"
          restart: "always"
          wanted_by: "multi-user.target"
        kissattach:
          enabled: Yes
          exec_start: "/usr/sbin/kissattach /dev/direwolf ax0"
          type: oneshot
          remain_after_exit: yes
          restart: "on-failure"
          requires: "socat.service"
          wanted_by: "multi-user.target"
        nrattach:
          enabled: Yes
          exec_start: "/usr/sbin/nrattach netrom"
          type: oneshot
          remain_after_exit: yes
          restart: "on-failure"
          requires: "kissattach.service"
          wanted_by: "multi-user.target"
        mheard:
          enabled: Yes
          exec_start: "/usr/sbin/mheardd"
          restart: "on-failure"
          requires: "kissattach.service"
          wanted_by: "multi-user.target"
        netrom:
          enabled: Yes
          exec_start: "/usr/sbin/netromd -i"
          type: oneshot
          remain_after_exit: yes
          restart: "on-failure"
          requires: "nrattach.service"
          wanted_by: "multi-user.target"
        ax25d:
          enabled: Yes
          exec_start: "/usr/sbin/ax25d -l"
          restart: "on-failure"
          requires: "kissattach.service"
          wanted_by: "multi-user.target"
