---

- hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true
  vars_prompt:
    - name: callsign
      prompt: what is your callsign
      private: no
    - name: nralias
      prompt: what is your netrom alias (eg. LINUX or BBS)
      private: no
    - name: nrssid
      prompt: what is your netrom SSID number
      default: "1"
      private: no
    - name: nrpassword
      prompt: what is your netrom node password 
      private: yes
  roles:
    - role: ax25
      become: True
