all:
  children:
    packet:
      hosts:
        localhost:
          ansible_connection: local
      vars:
        callsign: "G7UOZ"
        nralias: "UOZNOD"
        nrpassword: "verysecret"
        nrport: 1
