---
- name: install direwolf packages
  ansible.builtin.package:
    name:
      - git
      - gcc
      - g++
      - make
      - cmake
      - libasound2-dev
      - libudev-dev
      - libavahi-client-dev
      - alsa-utils
    state: present
- name: Checkout direwolf dev
  ansible.builtin.git:
    repo: 'https://github.com/wb2osz/direwolf.git'
    dest: /opt/direwolf
    version: dev
  notify: build direwolf package
- name: /etc/direwolf
  ansible.builtin.file:
    path: /etc/direwolf
    state: directory
- name: copy templates
  ansible.builtin.template:
    src: templates/direwolf.conf.j2
    dest: /etc/direwolf/{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  register: direwolf_templates
  notify: direwolf service enabled
  loop: "{{ instances }}"
