---
- name: build direwolf package
  ansible.builtin.script:
    cmd: build_direwolf.sh
    notify: restart direwolf
- name: restart direwolf
  ansible.builtin.service:
    name: direwolf
    state: restarted
