---
- name: build direwolf package
  ansible.builtin.script:
    cmd: build_direwolf.sh
  notify: restart all direwolf
- name: restart direwolf
  loop: "{{ direwolf_templates.results | map(attribute='item') | map(attribute='name') | list }}"
  ansible.builtin.service:
    name: 'direwolf@{{ item }}'
    daemon_reload: yes
    state: restarted
- name: restart all direwolf
  ansible.builtin.command: /usr/bin/systemctl restart direwolf@*
