---
- name: build direwolf package
  ansible.builtin.script:
    cmd: build_direwolf.sh
  notify: restart all direwolf
- name: direwolf service enabled
  loop: "{{ direwolf_templates.results | map(attribute='item') | map(attribute='name') | list }}"
  ansible.builtin.systemd:
    name: direwolf@{{ item.name }}
    daemon_reload: yes
    enabled: yes
    state: started
  notify: restart direwolf
- name: restart direwolf
  loop: "{{ direwolf_templates.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  ansible.builtin.service:
    name: 'direwolf@{{ item }}'
    state: restarted
- name: restart all direwolf
  ansible.builtin.command: /usr/bin/systemctl restart direwolf@*
