---
# tasks file for ax25
- name: include direwolf role
  ansible.builtin.include_role:
    name: direwolf
  vars:
    instances:
      - name: "{{ instance.name }}"
        channels: "{{ instance.direwolf }}"
  loop: "{{ axports }}"
  loop_control:
    loop_var: instance
  when: instance.direwolf is defined

- name: set kiss module parameters
  ansible.builtin.copy:
    content: 'options mkiss crc_force=1' 
    dest: /etc/modprobe.d/mkiss.conf
    owner: root
    group: root
    mode: '0644'

- name: load kiss module
  modprobe:
    name: mkiss
    state: present

- name: load kiss module on boot
  ansible.builtin.copy:
    content: 'mkiss'
    dest: /etc/modules-load.d/mkiss.conf
    owner: root
    group: root
    mode: '0644'

- name: update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: install ax25 packages
  ansible.builtin.package:
    name:
      - ax25-apps
      - ax25-tools
      - socat
    state: present

- name: copy templates
  ansible.builtin.template:
    src: templates/{{ item }}.j2
    dest: /etc/ax25/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - ax25d.conf
    - axports
  notify: reload ax25d

- name: /dev/tnc directory
  ansible.builtin.file:
    path: /dev/tnc
    state: directory

- name: /dev/tnc kissattach path unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/kissattach@.path
    src: kissattach@.path

- name: remote tnc environment configuration directory
  ansible.builtin.file:
    path: /etc/systemd/system/socat@{{ item.name }}.service.d
    state: directory
  loop: "{{ axports }}"
  when: item.kissport is defined or item.direwolf is defined

- name: remote tnc environment configuration
  ansible.builtin.copy:
    dest: /etc/systemd/system/socat@{{ item.name }}.service.d/{{ item.name }}.conf
    content: |
      [Service]
      Environment="KISS_ADDRESS=TCP4:{{ item.kisshost | d('localhost', true) }}:{{ item.kissport }}"
  loop: "{{ axports }}"
  when: item.kissport is defined
  register: remote_tncs
  notify: 
    - enable local tnc link service
    - enable kissattach for all ports
    - enable ax25d

- name: remote tnc direwolf dependency
  ansible.builtin.copy:
    dest: /etc/systemd/system/socat@{{ item.name }}.service.d/{{ item.name }}.conf
    content: |
      [Service]
      Environment="KISS_ADDRESS=TCP4:localhost:{{ item.direwolf[0].kissport | d('8001', true) }}"

      [Unit]
      BindsTo=direwolf@{{ item.name }}.service
      After=direwolf@{{ item.name }}.service
  loop: "{{ axports }}"
  when: item.direwolf is defined

- name: local tnc environment configuration directory
  ansible.builtin.file:
    path: /etc/systemd/system/tnc_link@{{ item.name }}.service.d
    state: directory
  loop: "{{ axports }}"
  when: item.serialPort is defined

- name: local tnc environment configuration
  ansible.builtin.copy:
    dest: /etc/systemd/system/tnc_link@{{ item.name }}.service.d/{{ item.name }}.conf
    content: |
      [Service]
      Environment="SERIAL_PORT={{ item.serialPort }}"
  loop: "{{ axports }}"
  when: item.serialPort is defined
  register: local_tncs
  notify: 
    - enable local tnc link service
    - enable kissattach for all ports
    - enable ax25d

- name: dump direwolf port info
  ansible.builtin.debug:
    msg: "name: {{ item.name }} channels: {{ item.direwolf }}"
  loop: "{{ axports }}"
  when: item.direwolf is defined

- name: include netrom role
  ansible.builtin.include_role:
    name: netrom
  vars:
    nrports:
      - "{{ instance.netrom | combine( { 'axport': instance.name } ) }}"
  loop: "{{ axports }}"
  loop_control:
    loop_var: instance
  when: instance.netrom is defined
